version: '3'
services:
  app:
    container_name: ozanexchange
    image: ozanexchange
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - ozan-network
    environment:
      MONGO_URI: mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ozan-network
networks:
  ozan-network: